[package]
name = "split"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.37", features = ["derive"] }
daemonize = "0.5.0"
nix = { version = "0.29.0", features = ["process", "signal"] }
signal-hook = "0.3.17"
